### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by tonylomax** [fac18/week4-ABEH-autocomplete#38]
Really nice work, you got a solid MVP together and implemented completely new concepts seemingly without too much trouble. Amazing work! 

![elf](https://media.giphy.com/media/3otPoS81loriI9sO8o/giphy.gif)

**Comment by tonylomax** [comment]
Re-iterating this as you've done amazingly! Especially with the disruption yesterday, so... 

🎉🎉🎉🎉**CONGRATS!!** 🎉🎉🎉🎉

**Comment by bethanyios** [comment]
Thanks Tony 😁😁😁
