### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by tonylomax** [fac18/week4-ABEH-autocomplete#44]
Host it on Heroku and you'll have a legit web app 

![host](https://media.giphy.com/media/zRn5yy4hkE0Wk/giphy.gif)

**Comment by bethanyios** [comment]
We deployed almost a the beginning! Is it now working for you on the heroku app??? 
That is what Im seeing it on 
![Screen Shot 2019-11-22 at 11 05 35](https://user-images.githubusercontent.com/36175966/69421101-158a9000-0d18-11ea-924a-058b6dac5410.png)
strange?

**Comment by bethanyios** [comment]
we hadnt linked it sorry!!
