### ISSUE TITLE
Dropdown slight glitch

### ISSUE THREAD

**Issue by rosalie-baxter** [fac18/week4-ABEH-autocomplete#57]
hey guys 

sometimes when I had already selected an option from the dropdown the menu still didn't disappear - I think because it was still registering as matching 

![search function](https://user-images.githubusercontent.com/45801475/69420406-87fa7080-0d16-11ea-82e2-7c836ea067ca.png)

for an enhancement to UI, if you add in an extra bit to your search function saying that if the input and the suggestion are an exact match then not to show the suggestion? I cloned your repo and added the below and it worked, though there may also be a way you can do it still keeping in your RegExp :)

![searchFunctionAmend](https://user-images.githubusercontent.com/45801475/69420315-584b6880-0d16-11ea-8021-0765239c42f9.png)

**Comment by sleepysnapdragon** [comment]
super suggestion, it worked perfectly, thanks! and we managed to keep the regex :)
